include:
  # this provides various docker build/tag/push logic. Make Sure the environment Variables are set
  # - DOCKER_LOGIN
  # - DOCKER_PASSWORD
  # - DOCKER_REGISTRY
  - project: "gitlab/pipeline/jobs/docker"
    ref: master
    file: "/templates/build-push-linux-general.yml"
  - project: "gitlab/pipeline/jobs/node"
    ref: master
    file:
      # this is needed for al the other node templates to work
      - "/templates/base.yml"
      # - "/templates/test.yml"
      # TODO to enable an npm ci:doc and properly npm run ci:cover must be present
      # - '/templates/doc.yml'
      # - '/templates/coverage.yml'
      # - '/templates/build.yml'

# overwrite the necessary variables so the docker images fit the actual ones:
.docker-builds:
  variables:
    REGISTRY_IMAGE: "$DOCKER_REGISTRY/api-mgmt/devportal-v2"
workflow:
  rules:
    # Merge requests runs in different context (detached context) and therefore need to specify extra
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
      # Build all Branches, but ignore Merge Requests, otherwise 2 Pipelines will be created
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS == null
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "pas-release"
      # Build v2 branch TODO remove
    - if: $CI_COMMIT_BRANCH == "Dev-Portal-2.0"

stages:
  - build
