name: Docker Pull Request CI

on:
  pull_request:

jobs:
  read-versions:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.read-apiman-versions.outputs.release-version }}
      snapshot-version: ${{ steps.read-apiman-versions.outputs.snapshot-version }}
    steps:
      - name: Checkout Apiman Docker repo
        uses: actions/checkout@v3

      - name: Default setup items
        run: bash .github/workflows/support/setup.sh

      - name: "Get release and snapshot versions..."
        id: read-apiman-versions
        run: |
          echo "::set-output name=release-version::$(cat .github/workflows/RELEASE_VERSION)"
          echo "::set-output name=snapshot-version::$(cat .github/workflows/SNAPSHOT_VERSION)"

  build-against-release:
    needs: read-versions
    uses: apiman/apiman-docker/.github/workflows/docker-test-release.yml@master
    secrets: inherit
    with:
      apiman-version: ${{ needs.read-versions.outputs.release-version }}
      push-to-repos: false
      snapshot: false

  build-against-snapshot:
    needs: read-versions
    uses: apiman/apiman-docker/.github/workflows/docker-test-release.yml@master
    secrets: inherit
    with:
      apiman-version: ${{ needs.read-versions.outputs.snapshot-version }}
      push-to-repos: false
      snapshot: true


