name: Docker Pull Request CI

on:
  pull_request:

jobs:
  read-version:
    runs-on: ubuntu-latest
    outputs:
      snapshot-version: ${{ steps.check-version-change.outputs.snapshot-version }}
      release-version: ${{ steps.check-version-change.outputs.snapshot-version }}
    steps:
      - name: "Get release and snapshot versions..."
        run: |
          echo "{release_version=$(cat .github/workflows/RELEASE_VERSION)}" >> $GITHUB_ENV
          echo "{snapshot_version=$(cat .github/workflows/SNAPSHOT_VERSION)}" >> $GITHUB_ENV

  build-against-release:
    needs: read-version
    uses: apiman/apiman-docker/.github/workflows/docker-test-release.yml@master
    secrets: inherit
    with:
      apiman-version: ${{ needs.read-version.outputs.release-version }}
      push-to-repos: false
      snapshot: false

  build-against-snapshot:
    needs: read-version
    uses: apiman/apiman-docker/.github/workflows/docker-test-release.yml@master
    secrets: inherit
    with:
      apiman-version: ${{ needs.read-version.outputs.snapshot-version }}
      push-to-repos: false
      snapshot: true


