name: update Apiman snapshot version

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - apiman-snapshot-version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Apiman Docker repo
        uses: actions/checkout@v3

      - name: Update snapshot version in docker-release flow if changed
        id: check-version-change
        run: |
          SNAPSHOT_VERSION_FILE=$(cat .github/workflows/SNAPSHOT_VERSION)
          if [[ "$SNAPSHOT_VERSION_FILE" !=  "${{ github.event.client_payload.snapshot_version }}" ]] 
          then
            echo "Old version: $SNAPSHOT_VERSION_FILE - New version: ${{ github.event.client_payload.snapshot_version }}"
            echo ${{ github.event.client_payload.snapshot_version }} > .github/workflows/SNAPSHOT_VERSION
            echo ::set-output name=snapshot-version-changed::true
          else
            echo "Snapshot version was not changed"
            echo ::set-output name=snapshot-version-changed::false
          fi

      - name: Commit release snapshot update to repository
        uses: EndBug/add-and-commit@v7.2.1
        if: ${{ steps.check-version-change.outputs.snapshot-version-changed }}
        with:
          author_name: apiman-ci
          default_author: user_info
          message: "chore(ci): update SNAPSHOT_VERSION to ${{ github.event.client_payload.snapshot_version }}"
          add: .workflows --force
